  CREATE TABLE "CHTPZ"."DOCUMENT" 
   (	"DOC_DATE" DATE NOT NULL ENABLE, 
	"SUM" NUMBER(*,2) NOT NULL ENABLE, 
	"FIRM_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "DOCUMENT_FK1" FOREIGN KEY ("FIRM_ID")
	  REFERENCES "CHTPZ"."FIRM" ("FIRM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GARNET" ;